apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: $TABLE_NAME
spec:
  tableName: $TABLE_NAME
  attributeDefinitions:
    - attributeName: ForumName
      attributeType: S
    - attributeName: Subject
      attributeType: S
    - attributeName: LastPostDateTime
      attributeType: S
  keySchema:
    - attributeName: ForumName
      keyType: HASH
    - attributeName: Subject
      keyType: RANGE
  localSecondaryIndexes:
    - indexName: LastPostIndex
      keySchema:
        - attributeName: ForumName
          keyType: HASH
        - attributeName: LastPostDateTime
          keyType: RANGE
      projection:
        projectionType: KEYS_ONLY
  provisionedThroughput:
    readCapacityUnits: 5
    writeCapacityUnits: 5
  streamSpecification:
    streamEnabled: true
    streamViewType: "NEW_AND_OLD_IMAGES"
